### ISSUE TITLE
the input text format is out of order

### ISSUE THREAD

**Issue by imztone** [Burutiaowuhh/smallchat-study#1]
Bug
![image](https://github.com/Burutiaowuhh/smallchat-study/assets/33047106/7740d1ab-d666-4129-95dd-a018625c29e9)

**Comment by Burutiaowuhh** [comment]
请提供你的电脑型号、软件及版本，谢谢

**Comment by Burutiaowuhh** [comment]
> Bug ![image](https://user-images.githubusercontent.com/33047106/284147404-7740d1ab-d666-4129-95dd-a018625c29e9.png)

请提供你的电脑型号、软件及版本，谢谢

**Comment by imztone** [comment]
> > Bug ![image](https://user-images.githubusercontent.com/33047106/284147404-7740d1ab-d666-4129-95dd-a018625c29e9.png)
> 
> 请提供你的电脑型号、软件及版本，谢谢
🌹
